#!/bin/bash

# Output our ASCII banner showing that we're running cspray.sh
cat ./ascii/cspray-arch-kde.txt

echo ""
echo ""

echo "Starting to install and configure your ArchLinux distribution to be configured according to the opinions of cspray!"

source ./packages.sh
# Make sure our scripting language of choice is installed
sudo pacman -Syq --noconfirm --noprogressbar --needed ${installPackages[*]}

echo "Finished installing necessary packages!"
echo "Starting to configure your installation..."
echo ""

./bin/setup-timedate
./bin/setup-credentials

# TODO make sure git config is setup: default user name, default global gitignore
# TODO make sure spray-zsh is setup with default plugins

# We need to echo out a blank line so zsh doesn't output an erroneous % sign
echo ""
