#!/bin/bash

# Output our ASCII banner showing that we're running cspray.sh
cat ./ascii/cspray-arch-kde.txt

echo; echo

# Give the user a chance to cancel out of the installation process
echo -n "Will configure your ArchLinux KDE distribution in"
counter=5
while [ $counter -ge 1 ]; do
  echo -n " ... $counter"
  if [ $counter -eq 1 ]; then
    echo "!"
  fi
  sleep 1
  ((counter--))
done

echo

setup_scripts=(
  sanity-check
  setup-credentials
  setup-packages
  setup-timedate
  setup-git
  setup-spray-zsh
)

for setup_script in ${setup_scripts[*]}; do
  if ! "./bin/${setup_script}"; then
    echo -e "\e[31mEncountered unexpected errors running ${setup_script}!\e[0m"
    exit $?
  fi
done
# TODO setup gopass

# We need to echo out a blank line so zsh doesn't output an erroneous % sign
echo
